#opt
train_epoch: 50           # number of epochs
warmup_epoch: 0    # number of warm-up epochs
wd: 0.000001               # weight decay
lr: 0.00001
min_lr: 0

#dset
dataset: BRACS
B: 1
n_class: 3                            # number of classes
data_dir: './Feature/BRACSFeature/patch_feats_pretrain_medical_ssl.h5'         # directory of dataset
n_worker: 0                          # number of workers
pin_memory: False                     # use pin memory in dataloader
n_shot: -1

# pretrained
backbone: 'ViT-S/16'
pretrain: 'medical_ssl'
D_feat: 384
D_inner: 128
